# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer_tbl',
            },
        ),
    ]
